#!/usr/bin/env bash
set -euxo pipefail

docker build . -t jdxcode/chim:arch --platform linux/amd64
docker run -it --rm --mount type=bind,source="$PWD/..",target=/home/jdxcode/aur --platform linux/amd64 jdxcode/chim:arch
